[package]
name = "sloppy-compressor"
version = "0.1.0"
authors = ["Neil Williams <neil.williams@growthstreet.co.uk>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
